#+TITLE: Jin-Cheng Guu
#+AUTHOR: Jin
#+EMAIL: jin-cheng.guu@stonybrook.edu
#+OPTIONS: ':t *:t -:t ::t <:t \n:nil ^:t arch:headline author:t c:nil
#+OPTIONS: creator:comment d:(not LOGBOOK) date:t e:t email:t f:t inline:t
#+OPTIONS: num:nil p:nil pri:nil stat:t tags:t tasks:t tex:dvipng timestamp:t toc:nil
#+OPTIONS: todo:t |:t
#+CREATOR:
#+DESCRIPTION:
#+EXCLUDE_TAGS: noexport
#+KEYWORDS:
#+LANGUAGE:
#+SELECT_TAGS: export
#+HTML_HEAD: <link rel="stylesheet" href="./style.css" />

[[./index.html][Home]] | [[./research.html][Research]] | [[./teaching.html][Teaching]]

* Research

** Publications

+ [3] [[https://arxiv.org/abs/2206.04570][Equivalence of field theories: Crane-Yetter and the shadow]],
  arXiv:2206.04570.

+ [2] [[https://arxiv.org/abs/2111.06919][Explicit Factorization of a Categorical Center]] (joint with
  Ying Hong Tham), arXiv:2111.06919, submitted to Communications
  in Mathematical Physics.

+ [1] [[https://arxiv.org/abs/2107.05914][Categorical Center of Higher Genera and 4D Factorization
  Homology]], arXiv:2107.05914, submitted to Quantum Topology.

** Description

+ *Crane-Yetter theory in dimension two*

  Crane-Yetter theory (CY) is expected to be a fully extended
  4D-TQFT, generalizing the 3D Witten-Reshetikhin-Turaev model.
  In [3], we showed that the Crane-Yetter invariant for closed
  4-manifolds coincide with the shadow invariant (a la V.
  Turaev). In [2], we use the idea from Crane-Yetter theory to
  explicitly construct the inverse functor of the natural one C^{2}
  \to Z(C) from the square of a modular category to its Drinfeld
  center.

  In dimension 2, it provides invariants for the underlying
  category as well. For example, CY with the 2-punctured 2-sphere
  reproduces the Drinfeld center of the underlying fusion
  category. Given the importance of Drinfeld center, it is
  natural to ask what other surfaces provide. In [1], we gave an
  explicit construction.

+ *(q,t) -deformation of knot amplitudes*

  Quantum 6j-symbols are numerical presentations of the monoidal
  structures for the quantum group Rep(U_{q}(g)). Their squares seem
  to admit (q,t)-deformations by the numerical evidence
  discovered by Shamil Shakirov and Semeon Arthamonov. We aim to
  find a theoretic basis for such (q,t)-deformation.

+ *Matrix-valued symmetric Macdonald polynomials*

  Alexander Kirillov and Pavel Etingof found a link between
  Macdonald symmetric polynomials and the generalized traces of
  (special) representations of quantum groups (type A) in the
  90s. It is natural to consider all representations instead, and
  ask for the properties of the corresponding matrix-valued
  symmetric polynomials.
